---
  - name: create swap file
    shell: fallocate -l 1G /var/swap

  - name: mkswap swap
    shell: mkswap /var/swap

  - name: set swap permissions
    file: 
     path: /var/swap
     mode: 0600

  - name: Turn Swap on
    shell: swapon /var/swap

  - name: Add swap to fstab
    action: lineinfile dest=/etc/fstab regexp="swap" line="/var/swap               none                    swap    defaults        0 0" state=present

