---
- name: restart-sshd
  shell: systemctl restart sshd

- name: restart apache
  service:
        name: httpd
        state: restarted
        enabled: yes

- name: mariadb
  service:
        name: mariadb
        state: restarted
        enabled: yes

