---
- hosts: webservers
  user: root
  connection: ssh
  port: 8888
  vars:
        last_db: "{{ lookup('pipe', 'find files/db_dumps/ -type f -mmin -600 | sort -r | head -n 1') }}" 

  pre_tasks:
  - name: include vars
    include_vars: vars/db.yml
  - name: debug last db var
    debug: var=last_db

  tasks:
  - name: dump current db
    mysql_db:
        name: '{{ db_name }}'
        state: dump
        target: /backup/db/{ lookup('pipe', 'date +%Y%m%d-%H%M') }}/{{ db_name}}.sql

  - name: drop db
    mysql_db:
         name: '{{ db_name }}'
         state: absent

  - name: create new empty db
    mysql_db:
         name: '{{ db_name }}'
         state: present

  - name: assign user to db
    mysql_user:
         name: '{{ db_user }}'
         priv: '*.*:ALL'
         state: present


  - name: copy last db backup
    copy:
        src: '{{ last_db }}'
        dest: /tmp/{{ last_db }}

  - name: import db
    mysql_db:
        name: '{{ last_db }}' 
        state: import
        target: /tmp/{{ last_db }}

